
//export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"
export const CHANGE_PAGE="CHANGE_PAGE"
export const LOGIN="LOGIN"
export const BEACONLIST="BEACONLIST"
export const BEACONDETAIL="BEACONDETAIL"
export const BEACONEDIT="BEACONEDIT"
export const PROFILE="PROFILE"
export const LOSTBEACONLIST="LOSTBEACONLIST"
export const ADDLOSTBEACON="ADDLOSTBEACON"
//action types belirlendi 